### ISSUE TITLE
unsupported logical type System.Nullable`1[System.Char]

### ISSUE THREAD

**Issue by dburtsev** [G-Research/ParquetSharp#249]
VS Code. Windows 10. x64
The code works with int, string but not with Char
Unhandled exception. System.ArgumentException: unsupported logical type System.Nullable`1[System.Char]
   at ParquetSharp.Column.CreateSchemaNode(LogicalTypeFactory logicalTypeFactory, Type type, String name, LogicalType logicalTypeOverride, Int32 length)
   at ParquetSharp.Column.CreateSchemaNode(LogicalTypeFactory typeFactory)
   at ParquetSharp.Column.<>c__DisplayClass9_0.<CreateSchemaNode>b__0(Column c)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at ParquetSharp.Column.CreateSchemaNode(Column[] columns, LogicalTypeFactory logicalTypeFactory, String nodeName)
   at ParquetSharp.Column.CreateSchemaNode(Column[] columns, String nodeName)
   at ParquetSharp.ParquetFileWriter..ctor(String path, Column[] columns, Compression compression, IReadOnlyDictionary`2 keyValueMetadata)
   at testChar.Program.Main(String[] args) in C:\Work\Parquet\testChar\Program.cs:line 49

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using System.IO;
using ParquetSharp;

namespace testChar
{
    class Program
    {
        static void Main(string[] args)
        {
            var num16Array = new Int16?[] { };
            var numArray = new int?[] { };
            var dtArray = new DateTime?[] {};
            var strArray = new string?[] { };
            var num64Array = new Int64?[] { };
            var boolArray = new bool?[] { };
            var charArray = new char?[] { };
            System.Data.DataTable dt = new System.Data.DataTable();
            System.Data.DataColumn column = new System.Data.DataColumn("id", typeof(Int32));
            dt.Columns.Add(column); 
            column = new System.Data.DataColumn("Chr", typeof(char));
            dt.Columns.Add(column);                        

            DataRow row = dt.NewRow();
            row["id"] = 1;
            row["Chr"] = 'A';
            dt.Rows.Add(row);
            row = dt.NewRow();
            row["id"] = DBNull.Value;
            row["Chr"] = DBNull.Value;
            dt.Rows.Add(row);

            var columns = new ParquetSharp.Column[dt.Columns.Count];

            for (int i = 0; i < dt.Columns.Count; i++)
            {
                switch (dt.Columns[i].DataType.Name)
                {
                    case "Int32": columns[i] = new ParquetSharp.Column<int?>(dt.Columns[i].ColumnName); break;
                    case "Char": columns[i] = new ParquetSharp.Column<char?>(dt.Columns[i].ColumnName); break;
                }
            }

            using var file = new ParquetFileWriter("C:\\Work\\Parquet\\test.parquet", columns);
            using var rowGroup = file.AppendRowGroup();            
            for (int i = 0; i < dt.Columns.Count; i++)
            {
                switch (dt.Columns[i].DataType.Name)
                {                  
                    case "Int32": {
                        numArray = dt.AsEnumerable().Select(d => d.Field<int?>(dt.Columns[i].ColumnName)).ToArray();
                        using (var intWriter = rowGroup.NextColumn().LogicalWriter<int?>())
                        {
                            intWriter.WriteBatch(numArray);
                        }
                        break;
                    }  
                    case "Char": { charArray = dt.AsEnumerable().Select(d => d.Field<char?>(dt.Columns[i].ColumnName)).ToArray();
                    using (var charWriter = rowGroup.NextColumn().LogicalWriter<char?>())
                        {
                            charWriter.WriteBatch(charArray);
                        }
                        break;
                    }                     
                }
            }
            file.Close();
            Console.WriteLine("End");
            System.Environment.Exit(0);
        }
    }
}
```

**Comment by adamreeve** [comment]
Hi, there isn't a logical type in the Parquet format that directly corresponds to .NET's Char type, so you'll probably need to convert these to a different type before writing. The most suitable approach is probably writing a Char as a ushort/UInt16.

**Comment by dburtsev** [comment]
Thanks @adamreeve
