### ISSUE TITLE
decimal type requires a DecimalLogicalType override

### ISSUE THREAD

**Issue by dburtsev** [G-Research/ParquetSharp#250]
VS Code. Windows 10 x64
Unhandled exception. System.ArgumentException: decimal type requires a DecimalLogicalType override
```
var columnDec = new ParquetSharp.Column<decimal?>("DecColumn");
```
How can I use DecimalLogicalType override?
Thanks

**Comment by adamreeve** [comment]
The logical type override is an optional argument to the column constructor, eg:
```c#
var columnDec = new ParquetSharp.Column<decimal?>("DecColumn", LogicalType.Decimal(29, 3));
```

The Parquet decimal format doesn't correspond exactly to .NET's decimal type, so you need to specify the precision and scale required. See [the parquet logical type docs](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal) for an explanation of how these work. Currently only a precision of 29 is supported, which matches .NET's decimal type precision.

**Comment by MarkPflug** [comment]
@dburtsev  I think you might be looking to convert a DataTable to parquet? I saw your question over on the Parquet.NET repo as well. Here is a gist I just put together to compare these libraries:

https://gist.github.com/MarkPflug/c13fd63d787d011b594784fa26133911

It implements an extension method for DbDataReader (which you can create over a DataTable), which allows you do write to a parquet file as a one-liner:
```
DataTable myData = ...;
myData.CreateDataReader().WriteParquetSharp("myData.parquet");
```
I haven't thoroughly tested it; I literally just finished getting it working, so there might be bugs, but it worked for my dataset which included decimal columns (thanks @adamreeve for your pointer here, which is exactly what I needed!).

For what it's worth, this library appears to be somewhat faster, and also creates a smaller file.

Feel free to use the code in my gist if you find it useful. I can't guarantee anything with regard to quality, or correctness, but it did manage to produce a parquet file with my test data.

**Comment by dburtsev** [comment]
Thank you @MarkPflug 
This is my task:
ETL will query SQL Server database and copy one table to the Redshift database. The current version use .csv files.
Step 1 - get table name as parameter
Step 2 - Create ADODB.Connection, ADODB.Recordset, OleDbDataAdapter, DataTable
Step 3 - query INFORMATION_SCHEMA.COLUMNS and create SELECT statement for the table
Step 4 - get table rows count 
SELECT p.rows AS RowCounts
FROM sys.tables t 
INNER JOIN sys.indexes i ON t.OBJECT_ID = i.object_id
INNER JOIN sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id
INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE s.name = 'dbo' AND t.name = 'xyz' 
GROUP BY t.name, s.name, p.rows;

Step 5 - Set Recordset.CacheSize = table rows count. This is not possible with DbDataReader. CacheSize speeds up the process.
Step 6 - OleDbDataAdapter.Fill(DataTable, ADODB.Recordset);
Now I have DataTable and I would like to save it as a Parquet file

My guess is that LINQ will query DataTable faster than DbDataReader.

**Comment by MarkPflug** [comment]
So, you're just trying to capture all the data from a specific SQL table? That is exactly what I needed too, but you have some intermediate steps I didn't bother with. I use System.Data.SqlClient, and just did a "select * from table", `ExecuteDataReader()`, then `WriteParquetSharp`. I don't know what CacheSize is. Anyway, feel free to use the code in the gist if you find it helpful. Good luck.

**Comment by dburtsev** [comment]
You can't use "select * from table" to copy data between different servers. What if your source server has some specific data type?
In this case, you should cast/convert them to the destination server data type. I do it in the select statement. This is why I must generate select in runtime.

**Comment by dburtsev** [comment]
Hi @adamreeve 
I got Unhandled exception. System.NotSupportedException: only 29 digits of precision is currently supported for decimal type
   at ParquetSharp.Column..ctor(Type logicalSystemType, String name, LogicalType logicalTypeOverride, Int32 length)
   at ParquetSharp.Column..ctor(Type logicalSystemType, String name, LogicalType logicalTypeOverride)
   at ParquetSharp.Column`1..ctor(String name, LogicalType logicalTypeOverride)
   at ReadLineTest.Program.Main(String[] args) in C:\Work\C#\ReadLineTest\Program.cs:line 14

```
using System;
using System.Collections.Generic;
using ParquetSharp;
namespace ReadLineTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Version: {0}", Environment.Version.ToString());
            var columns = new ParquetSharp.Column[1];
            int precision = 18;
            int scale = 2;
            columns[0] = new ParquetSharp.Column<decimal?>("DecColumn", LogicalType.Decimal(precision, scale));
        }
    }
}
```

**Comment by adamreeve** [comment]
Hi @dburtsev, yes, currently only 29 digits of precision is supported. This should be sufficient to match the precision of a .Net decimal.

**Comment by dburtsev** [comment]
So precision is a constant, not a variable. I though that 29 is maximum value. Now I know this is a constant.
Please update documentation.
